name: 'Start Turborepo Cache Server'
inputs:
  turborepo-remote-cache-bucket-name:
    required: true
    description: 'The name of the S3 bucket to use for the remote cache'
  turborepo-remote-cache-access-key:
    required: true
    description: 'The access key for the S3 bucket'
  turborepo-remote-cache-secret-key:
    required: true
    description: 'The secret key for the S3 bucket'
runs:
  using: 'composite'
  steps:
  - name: Start Turborepo Cache Server
    uses: brunojppb/turbo-cache-server@2.0.2
    env:
      PORT: "8585"
      S3_BUCKET_NAME: ${{ inputs.turborepo-remote-cache-bucket-name }}
      S3_REGION: "us-west-2"
      S3_ACCESS_KEY: ${{ inputs.turborepo-remote-cache-access-key }}
      S3_SECRET_KEY: ${{ inputs.turborepo-remote-cache-secret-key }}
      S3_USE_PATH_STYLE: false
      MAX_PAYLOAD_SIZE_IN_MB: "100"
