packages:
  - packages/configs/*
  - packages/common/*
  - packages/docs/*
  - packages/frameworks/*

catalog:
  '@analogjs/platform': 2.0.0-beta.4
  '@analogjs/vite-plugin-angular': 2.0.0-beta.4
  '@analogjs/vitest-angular': 2.0.0-beta.4
  '@angular-devkit/architect': 0.2001.0
  '@angular-devkit/build-angular': ~20.3.5
  '@angular-devkit/core': ~20.3.5
  '@angular/animations': ~20.3.4
  '@angular/cdk': ~20.2.8
  '@angular/cdk-experimental': ~20.2.8
  '@angular/cli': ~20.3.5
  '@angular/common': ~20.3.4
  '@angular/compiler': ~20.3.4
  '@angular/compiler-cli': ~20.3.4
  '@angular/core': ~20.3.4
  '@angular/forms': ~20.3.4
  '@angular/platform-browser': ~20.3.4
  '@angular/platform-browser-dynamic': ~20.3.4
  '@angular/platform-server': ~20.3.4
  '@angular/router': ~20.3.4
  '@angular/ssr': ~20.3.5
  '@react-router/dev': 7.9.4
  '@react-router/express': 7.9.4
  '@react-router/node': 7.9.4
  '@react-router/remix-routes-option-adapter': 7.9.4
  '@react-router/serve': 7.9.4
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.1
  '@typescript-eslint/eslint-plugin': ^8.40.0
  '@typescript-eslint/parser': ^8.40.0
  '@typescript-eslint/utils': ^8.40.0
  eslint: ^9.37.0
  react: 19.2.0
  react-dom: 19.2.0
  react-router: 7.9.4
  tsx: 4.20.6
  typescript-eslint: ^8.40.0
  typescript: 5.8.3

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@angular/build'
  - '@angular-devkit/architect'
  - '@angular-devkit/build-angular'
  - '@angular-devkit/build-webpack'
  - '@angular-devkit/core'
  - '@angular-devkit/schematics'
  - '@angular/animations'
  - '@angular/cdk'
  - '@angular/cdk-experimental'
  - '@angular/cli'
  - '@angular/common'
  - '@angular/compiler'
  - '@angular/compiler-cli'
  - '@angular/core'
  - '@angular/forms'
  - '@angular/language-service'
  - '@angular/platform-browser'
  - '@angular/platform-browser-dynamic'
  - '@angular/platform-server'
  - '@angular/router'
  - '@angular/ssr'
  - '@qui/esbuild'
  - '@ngtools/webpack'
  - '@schematics/angular'
  - '@types/react'
  - '@types/react-dom'
  - react
  - react-dom

onlyBuiltDependencies:
  - '@bundled-es-modules/glob'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - aws-sdk
  - core-js-pure
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - style-dictionary
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver

#patchedDependencies:
#  '@react-router/dev@7.9.4': patches/@react-router__dev@7.9.4.patch
#  ng-packagr: patches/ng-packagr.patch
