packages:
  - packages/configs/*
  - packages/common/*
  - packages/debug-apps/*
  - packages/docs/*
  - packages/frameworks/*

autoInstallPeers: true

catalog:
  '@analogjs/platform': 2.0.4
  '@analogjs/vite-plugin-angular': 2.0.4
  '@analogjs/vitest-angular': 2.0.4
  '@angular-devkit/architect': 0.2003.10
  '@angular-devkit/build-angular': ~20.3.10
  '@angular-devkit/core': ~20.3.10
  '@angular/build': ~20.3.10
  '@angular/cdk': ~20.2.13
  '@angular/cdk-experimental': ~20.2.13
  '@angular/cli': ~20.3.10
  '@angular/common': ~20.3.12
  '@angular/compiler': ~20.3.12
  '@angular/compiler-cli': ~20.3.12
  '@angular/core': ~20.3.12
  '@angular/forms': ~20.3.12
  '@angular/platform-browser': ~20.3.12
  '@angular/platform-browser-dynamic': ~20.3.12
  '@angular/platform-server': ~20.3.12
  '@angular/router': ~20.3.12
  '@angular/ssr': ~20.3.10
  '@eslint/js': 9.37.0
  '@react-router/dev': 7.9.4
  '@react-router/express': 7.9.4
  '@react-router/node': 7.9.4
  '@react-router/remix-routes-option-adapter': 7.9.4
  '@react-router/serve': 7.9.4
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@typescript-eslint/eslint-plugin': 8.46.2
  '@typescript-eslint/parser': 8.46.2
  '@typescript-eslint/utils': 8.46.2
  esbuild: 0.25.11
  react: 19.2.0
  react-dom: 19.2.0
  react-router: 7.9.4
  tsx: 4.20.6
  typescript-eslint: 8.40.0

onlyBuiltDependencies:
  - '@bundled-es-modules/glob'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - aws-sdk
  - core-js-pure
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - style-dictionary
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver

patchedDependencies:
  '@react-router/dev@7.9.4': patches/@react-router__dev@7.9.4.patch
