// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {createImportModEntries} from "../mod-imports"
import type {ImportTransformEntry} from "../transformers"

export const mdxDocs: ImportTransformEntry[] = createImportModEntries(
  "@qui/mdx-docs",
  [
    // re-exports from @qui/mdx-docs-common were removed
    {
      imports: ["SiteData"],
      targetPackage: "@qui/mdx-docs-common",
    },
    // the rest of these entries are @qui/mdx-docs imports.
    {
      imports: [
        "DocsLayoutProps",
        "DocsLayout",
        "AnchorHeaderProps",
        "AnchorHeader",
        "Pre",
        "TocLinkProps",
        "TocLink",
        "AppContentProps",
        "AppContent",
        "BreadcrumbsProps",
        "Breadcrumbs",
        "ContentWrapperProps",
        "ContentWrapper",
        "DocsFooterProps",
        "DocsFooter",
        "Layout",
        "MainContentProps",
        "MainContent",
        "PageLinksProps",
        "PageLinks",
        "getPageLinks",
        "RootProps",
        "Root",
        "SidebarProps",
        "Sidebar",
        "childListStyle",
        "TableOfContents",
        "MdxDocsLayoutContextState",
        "useMdxDocsLayoutContext",
        "MdxDocsLayoutContextProvider",
        "MdxProvider",
        "TableOfContents",
        "TocHighlightStrategy",
        "RenderLink",
        "DocPropsSettings",
        "DocsLayoutSettings",
      ],
      targetPackage: "@qui/mdx-docs/docs-layout",
    },
    {
      imports: [
        "DocsExternalLink",
        "PropDefaultProps",
        "PropDefault",
        "PropDescriptionFunctionArgs",
        "PropDescriptionInlineTag",
        "PropDescriptionOptionTags",
        "PropDescriptionSeeTags",
        "PropDescriptionSummary",
        "PropDescriptionProps",
        "PropDescription",
        "PropName",
        "PropType",
        "Reference",
        "SimpleType",
        "TsIconProps",
        "TsIcon",
        "TypeInfoPopup",
        {name: "TypedocPropsProps", renameTo: "TypeDocPropsProps"},
        "getInterfaceTags",
        "TypeDocProps",
        "TypedocPropsListProps",
        "TypedocPropsList",
        "TypedocPropsTableProps",
        "TypedocPropsTable",
        "PropsContextValue",
        "usePropsContext",
        "PropsContextProvider",
        "DocPropsLayout",
        "PropsLayoutState",
        "usePropsLayoutContext",
        "PropsLayoutProvider",
        "TypeDocContextValue",
        "useTypeDocContext",
        "TypeDocContextProvider",
      ],
      targetPackage: "@qui/mdx-docs/typedoc",
    },
    {
      imports: [
        "CodeDemoProps",
        "CodeDemo",
        "CodeSource",
        "CodeDemoNode",
        "PreviewBlock",
        "ExtractedPreview",
        "extractPreviewsAndCleanSource",
        "isPreviewLine",
        "CodeEditorProps",
        "CodeEditor",
        "CopyButtonProps",
        "CopyButton",
        "EditableCodeDemoProps",
        "EditableCodeDemo",
        "QdsCodeDemoProps",
        "QdsCodeDemo",
        "removePreviewComments",
        "formatPreview",
        "useLiveCodeEditor",
      ],
      targetPackage: "@qui/mdx-docs/code-demo",
    },
    {
      imports: [
        "sortChildren",
        "makeChildPath",
        "stopPropagation",
        "setChildrenProps",
        "TreeConfig",
        "useTreeContext",
        "TreeContextProvider",
        "TreeFileProps",
        "TreeFile",
        "TreeFolderProps",
        "TreeFolder",
        "TreeIndents",
        "TreeProps",
        "Tree",
      ],
      targetPackage: "@qui/mdx-docs/file-tree",
    },
    {
      imports: [
        "RunnerProps",
        "Runner",
        "transform",
        "normalizeCode",
        "Scope",
        "RunnerOptions",
        "UseRunnerProps",
        "UseRunnerReturn",
        "useRunner",
        "generateElement",
        "createRequire",
        "importCode",
      ],
      targetPackage: "@qui/mdx-docs/runner",
    },
    {
      imports: [
        "GroupedResultItemProps",
        "GroupedResultItem",
        "SearchResultItemProps",
        "SearchResultItem",
        "SiteSearchDesktop",
        "SiteSearchMobile",
        "useGroupedResults",
        "doSiteSearch",
        "useSiteSearch",
      ],
      targetPackage: "@qui/mdx-docs/site-search",
    },
    {
      imports: [
        "getExpandedItems",
        "buildSideNavItems",
        "QuiSideNavigationItem",
        "MdxSideNavItem",
        "MdxSiteData",
        "useSiteContext",
        "SiteContextProvider",
      ],
      targetPackage: "@qui/mdx-docs/site-map",
    },
    {
      imports: [
        "CopyToClipboardProps",
        "CopyToClipboard",
        "UseCopyToClipboardProps",
        "UseCopyToClipboard",
        "useCopyToClipboard",
      ],
      targetPackage: "@qui/mdx-docs/copy-to-clipboard",
    },
    {
      imports: [
        "PackageManager",
        "MdxDocsContextValue",
        "useMdxDocsContext",
        "MdxDocsProvider",
      ],
      targetPackage: "@qui/mdx-docs/mdx-docs-context",
    },
    {
      imports: ["HighlightProp", "HighlightMatches", "HighlightTerms"],
      targetPackage: "@qui/mdx-docs/highlight",
    },
    {
      imports: ["CodeHighlightProps", "CodeHighlight"],
      targetPackage: "@qui/mdx-docs/code-highlight",
    },
    {
      imports: ["NotFoundProps", "NotFound"],
      targetPackage: "@qui/mdx-docs/not-found",
    },
    {
      imports: ["NpmCommandTabsProps", "NpmInstallTabs"],
      targetPackage: "@qui/mdx-docs/npm-install-tabs",
    },
    {
      imports: ["DeprecatedModule"],
      targetPackage: "@qui/mdx-docs/deprecated-module",
    },
    {
      imports: ["ReactLogo"],
      targetPackage: "@qui/mdx-docs/react-logo",
    },
  ],
)
