// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import chalk from "chalk"
import type {Link, Root} from "mdast"
import {posix} from "node:path"
import {visit} from "unist-util-visit"

import type {PageMap} from "@qualcomm-ui/mdx-common"

export interface CollectedLink {
  fragment?: string
  sourceFile: string
  sourcePathname: string
  targetPathname: string
  url: string
}

export interface InvalidLink extends CollectedLink {
  reason: "fragment-not-found" | "page-not-found"
}

const externalPrefixes = ["https://", "http://", "mailto:", "tel:"]

function isExternal(url: string): boolean {
  return externalPrefixes.some((prefix) => url.startsWith(prefix))
}

/**
 * Resolves a raw markdown link URL into a pathname and optional fragment.
 * Returns null for external links that should be skipped.
 */
export function resolveLink(
  url: string,
  sourcePathname: string,
): {fragment?: string; pathname: string} | null {
  if (isExternal(url)) {
    return null
  }

  const [rawPath, fragment] = url.split("#", 2)

  let pathname: string
  if (!rawPath || rawPath === "./" || rawPath === ".") {
    pathname = sourcePathname
  } else if (rawPath.startsWith("/")) {
    pathname = rawPath
  } else {
    // Relative path — resolve against the source page's "directory"
    const sourceDir = sourcePathname.endsWith("/")
      ? sourcePathname
      : posix.dirname(sourcePathname)
    pathname = posix.resolve(sourceDir, rawPath)
  }

  // Normalize trailing slashes
  if (pathname !== "/" && pathname.endsWith("/")) {
    pathname = pathname.slice(0, -1)
  }

  return {fragment: fragment || undefined, pathname}
}

/**
 * Walks the AST and collects all internal links from a parsed MDX page.
 */
export function collectLinks(
  tree: Root,
  sourceFile: string,
  sourcePathname: string,
): CollectedLink[] {
  const links: CollectedLink[] = []

  visit(tree, "link", (node: Link) => {
    const resolved = resolveLink(node.url, sourcePathname)
    if (!resolved) {
      return
    }

    links.push({
      fragment: resolved.fragment,
      sourceFile,
      sourcePathname,
      targetPathname: resolved.pathname,
      url: node.url,
    })
  })

  return links
}

/**
 * Validates collected links against the fully assembled page map.
 * The optional `docPropIds` map provides additional valid fragment targets
 * generated by TypeDocProps on each page.
 */
export function validateLinks(
  links: CollectedLink[],
  pageMap: PageMap,
  docPropIds?: Record<string, Set<string>>,
): InvalidLink[] {
  const invalid: InvalidLink[] = []

  for (const link of links) {
    const page = pageMap[link.targetPathname]

    if (!page) {
      invalid.push({...link, reason: "page-not-found"})
      continue
    }

    if (link.fragment) {
      const inToc = page.toc?.some((h) => h.id === link.fragment)
      const inDocProps = docPropIds?.[link.targetPathname]?.has(link.fragment)
      if (!inToc && !inDocProps) {
        invalid.push({...link, reason: "fragment-not-found"})
      }
    }
  }

  return invalid
}

/**
 * Logs invalid links to the console grouped by source page.
 */
export function reportInvalidLinks(invalidLinks: InvalidLink[]): void {
  if (invalidLinks.length === 0) {
    return
  }

  const grouped = new Map<string, InvalidLink[]>()
  for (const link of invalidLinks) {
    const existing = grouped.get(link.sourcePathname) ?? []
    existing.push(link)
    grouped.set(link.sourcePathname, existing)
  }

  console.debug(
    `\n${chalk.yellowBright.bold(`Found ${invalidLinks.length} broken link${invalidLinks.length === 1 ? "" : "s"}:`)}`,
  )

  for (const [sourcePathname, links] of grouped) {
    console.debug(`\n  ${chalk.blueBright.bold(sourcePathname)}`)
    for (const link of links) {
      const reason =
        link.reason === "page-not-found"
          ? "page not found"
          : `fragment "#${link.fragment}" not found`
      console.debug(`    ${chalk.red("x")} ${link.url} — ${reason}`)
    }
  }

  console.debug("")
}
