// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import stylistic from "@stylistic/eslint-plugin"
import commentLength from "eslint-plugin-comment-length"
import importPlugin from "eslint-plugin-import"
import eslintPluginOxfmt from "eslint-plugin-oxfmt"
import perfectionist from "eslint-plugin-perfectionist"
import promisePlugin from "eslint-plugin-promise"
import eslintPluginUnicorn from "eslint-plugin-unicorn"
import unusedImportsPlugin from "eslint-plugin-unused-imports"
import {defineConfig} from "eslint/config"

import {typescriptLanguageOptions, typescriptPlugins} from "./base.js"

const oxlintParityRules = {
  "@typescript-eslint/no-dupe-class-members": "error",
  "@typescript-eslint/no-loss-of-precision": "error",
  "@typescript-eslint/no-redeclare": "off",
  "@typescript-eslint/no-unused-private-class-members": "error",
  "block-scoped-var": "error",
  "constructor-super": "error",
  curly: "error",
  eqeqeq: ["error", "smart"],
  "for-direction": "error",
  "getter-return": "error",
  "no-array-constructor": "off",
  "no-async-promise-executor": "error",
  "no-caller": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": "error",
  "no-const-assign": "error",
  "no-constant-binary-expression": "error",
  "no-constant-condition": "error",
  "no-debugger": "error",
  "no-delete-var": "warn",
  "no-dupe-class-members": "off",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-empty-static-block": "error",
  "no-eval": "error",
  "no-ex-assign": "error",
  "no-extend-native": "error",
  "no-extra-bind": "error",
  "no-extra-boolean-cast": "error",
  "no-func-assign": "error",
  "no-global-assign": "error",
  "no-implied-eval": "off",
  "no-import-assign": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-iterator": "error",
  "no-loss-of-precision": "off",
  "no-misleading-character-class": "error",
  "no-new-native-nonconstructor": "error",
  "no-new-wrappers": "error",
  "no-nonoctal-decimal-escape": "error",
  "no-obj-calls": "error",
  "no-object-constructor": "error",
  "no-redeclare": "off",
  "no-self-assign": "error",
  "no-self-compare": "error",
  "no-setter-return": "error",
  "no-shadow-restricted-names": "error",
  "no-sparse-arrays": "error",
  "no-this-before-super": "error",
  "no-unassigned-vars": "error",
  "no-unreachable": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unsafe-optional-chaining": "error",
  "no-unused-expressions": "off",
  "no-unused-labels": "error",
  "no-unused-private-class-members": "off",
  "no-unused-vars": "off",
  "no-useless-backreference": "error",
  "no-useless-catch": "error",
  "no-useless-concat": "error",
  "no-useless-escape": "warn",
  "no-useless-rename": "error",
  "no-with": "error",
  "object-shorthand": "error",
  "prefer-const": "error",
  "prefer-object-has-own": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  "promise/always-return": "warn",
  "promise/catch-or-return": "warn",
  "promise/no-multiple-resolved": "error",
  "promise/no-nesting": "error",
  "promise/no-new-statics": "error",
  "promise/no-return-in-finally": "warn",
  "promise/no-return-wrap": "error",
  "promise/param-names": "error",
  "promise/spec-only": "error",
  "require-yield": "error",
  "use-isnan": "error",
  "valid-typeof": "error",
}

const unicornRules = {
  "unicorn/no-await-in-promise-methods": "error",
  "unicorn/no-for-each": "warn",
  "unicorn/no-invalid-fetch-options": "error",
  "unicorn/no-invalid-remove-event-listener": "error",
  "unicorn/no-static-only-class": "error",
  "unicorn/no-unnecessary-await": "error",
  "unicorn/no-unreadable-iife": "error",
  "unicorn/no-useless-length-check": "error",
  "unicorn/prefer-array-find": "error",
  "unicorn/prefer-node-protocol": "error",
  "unicorn/prefer-set-size": "error",
  "unicorn/prefer-string-trim-start-end": "error",
}

export default defineConfig({
  languageOptions: typescriptLanguageOptions,
  name: "qui-style-guide",
  plugins: {
    ...typescriptPlugins,
    "@stylistic": stylistic,
    "comment-length": commentLength,
    import: importPlugin,
    oxfmt: eslintPluginOxfmt,
    perfectionist,
    promise: promisePlugin,
    unicorn: eslintPluginUnicorn,
    "unused-imports": unusedImportsPlugin,
  },
  rules: {
    ...oxlintParityRules,
    ...unicornRules,
    ...commentLength.configs["flat/recommended"].rules,
    "@stylistic/spaced-comment": ["error", "always", {block: {balanced: true}}],
    "@typescript-eslint/ban-ts-comment": "off",
    "@typescript-eslint/consistent-type-imports": [
      "error",
      {fixStyle: "inline-type-imports"},
    ],
    "@typescript-eslint/explicit-member-accessibility": [
      "error",
      {
        accessibility: "explicit",
        overrides: {
          accessors: "no-public",
          constructors: "off",
          methods: "no-public",
          parameterProperties: "off",
          properties: "no-public",
        },
      },
    ],
    "@typescript-eslint/no-empty-interface": "off",
    "@typescript-eslint/no-extra-semi": "off",
    "@typescript-eslint/no-import-type-side-effects": "error",
    "@typescript-eslint/no-var-requires": "off",
    "comment-length/limit-multi-line-comments": [
      "warn",
      {
        ignoreUrls: true,
        maxLength: 85,
      },
    ],
    "comment-length/limit-single-line-comments": [
      "warn",
      {
        ignoreUrls: true,
        maxLength: 85,
      },
    ],
    "import/newline-after-import": ["error", {count: 1}],
    "import/no-cycle": "off",
    "import/no-duplicates": ["error", {"prefer-inline": true}],
    "import/order": "off",
    "multiline-comment-style": ["off"],
    "no-case-declarations": "off",
    "no-duplicate-imports": "off",
    "no-inner-declarations": "off",
    "no-invalid-this": "off",
    "no-prototype-builtins": "off",
    "no-restricted-imports": [
      "error",
      {
        patterns: [
          {
            group: ["@qualcomm-ui/*/src/**/*"],
            message:
              "Relative imports from src directories are not allowed. Please ensure that the targeted dependency is exported properly from its module",
          },
          {
            group: ["@qualcomm-ui/*/src"],
            message: 'Remove "src" (import directly)',
          },
        ],
      },
    ],
    "no-restricted-syntax": [
      "error",
      {
        message: "Use `private` instead",
        selector:
          ":matches(PropertyDefinition, MethodDefinition) > PrivateIdentifier.key",
      },
    ],
    "no-undef": "off",
    "no-var": "error",
    "oxfmt/oxfmt": "error",
    "unused-imports/no-unused-imports": "error",
    "unused-imports/no-unused-vars": [
      "error",
      {
        args: "after-used",
        argsIgnorePattern: "^_",
        caughtErrors: "all",
        caughtErrorsIgnorePattern: "^",
        vars: "all",
        varsIgnorePattern: "^_",
      },
    ],
  },
})
