// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

export const datePickerClasses = {
  actions: "qui-date-picker__actions",
  clearTrigger: "qui-date-picker__clear-trigger",
  content: "qui-date-picker__content",
  control: "qui-date-picker__control",
  controlGroup: "qui-input__root qui-date-picker__control-group",
  divider: "qui-date-picker__divider",
  errorIndicator: "qui-input__error-indicator",
  errorText: "qui-input__error-text",
  headline: "qui-date-picker__headline",
  headlineLabel: "qui-date-picker__headline-label",
  headlineValue: "qui-date-picker__headline-value",
  hint: "qui-input__hint",
  input: "qui-input__input qui-date-picker__input",
  inputGroup: "qui-input__input-group qui-date-picker__input-group",
  inputIcon: "qui-date-picker__input-icon",
  label: "qui-input__label qui-date-picker__label",
  nextTrigger: "qui-date-picker__next-trigger",
  positioner: "qui-date-picker__positioner",
  presets: "qui-date-picker__presets",
  presetsTrigger: "qui-date-picker__presets-trigger",
  presetTrigger: "qui-date-picker__preset-trigger",
  prevTrigger: "qui-date-picker__prev-trigger",
  rangeSeparator: "qui-date-picker__range-separator",
  rangeText: "qui-date-picker__range-text",
  root: "qui-date-picker__root",
  table: "qui-date-picker__table",
  tableBody: "qui-date-picker__table-body",
  tableCell: "qui-date-picker__table-cell",
  tableCellTrigger: "qui-date-picker__table-cell-trigger",
  tableHead: "qui-date-picker__table-head",
  tableHeader: "qui-date-picker__table-header",
  tableRow: "qui-date-picker__table-row",
  trigger: "qui-date-picker__trigger",
  valueTags: "qui-date-picker__value-tags",
  view: "qui-date-picker__view",
  viewCloseTrigger: "qui-date-picker__view-close-trigger",
  viewControl: "qui-date-picker__view-control",
  viewTrigger: "qui-date-picker__view-trigger",
} as const
