apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qui-hpa
  namespace: qui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qui
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      # HPA CPU Utilization is based on request
      name: cpu
      target:
        type: Utilization
        averageUtilization: 175
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: 175