name: 'Start Turborepo Cache Server'

runs:
  using: 'composite'
  steps:
  - name: Restore cache
    uses: actions/cache/restore@v3
    with:
      path: .turbo-cache
      key: turbo-remote-cache-v1

  - name: Start Turborepo Cache Server
    uses: ./.github/actions/turborepo-remote-cache
    env:
      PORT: "8585"
      STORAGE_PROVIDER: "local"
      STORAGE_PATH: ".turbo-cache"
      STORAGE_PATH_USE_TMP_FOLDER: false
      MAX_PAYLOAD_SIZE_IN_MB: "100"

