FROM public.ecr.aws/docker/library/node:22-slim

WORKDIR /app

COPY . .

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

# install and build
RUN corepack enable
RUN pnpm install
RUN pnpm run build:react
RUN pnpm react-docs build
ENV NODE_ENV=production

EXPOSE 3000

CMD ["pnpm", "run", "-C", "packages/docs/react-docs", "start"]
