FROM public.ecr.aws/docker/library/node:lts-slim AS build

WORKDIR /app

COPY . .

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

RUN apt update && apt install -y git && rm -rf /var/lib/apt/lists/*

# install and build
RUN corepack enable
RUN pnpm install --frozen-lockfile
RUN pnpm run build:react
RUN pnpm react-vscode-docs build
ENV NODE_ENV=production

EXPOSE 3000

CMD ["pnpm", "run", "-C", "packages/docs/react-vscode-docs", "start"]
