FROM public.ecr.aws/docker/library/node:lts-slim

WORKDIR /app

COPY . .

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

RUN set -ex; \
   apt-get update; \
   apt-get install -y --no-install-recommends git lsof curl wget; \
   rm -rf /var/lib/apt/lists/*

# install and build
RUN corepack enable
RUN pnpm install --frozen-lockfile

RUN pnpm exec playwright install chromium --with-deps --only-shell

RUN pnpm run build
RUN pnpm angular-docs build:prod
ENV NODE_ENV=production

EXPOSE 3000

CMD ["pnpm", "run", "-C", "packages/docs/angular-docs", "start"]
