FROM public.ecr.aws/docker/library/node:lts-slim AS builder
WORKDIR /app
COPY . .
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

RUN apt-get update; \
   apt-get install -y --no-install-recommends ca-certificates python3 make g++ git wget; \
   mkdir -p /usr/local/share/ca-certificates/qualcomm.com; \
   rm -rf /var/lib/apt/lists/*

RUN wget -P /usr/local/share/ca-certificates/qualcomm.com \
   https://pki.qualcomm.com/qc_root_g2_cert.crt \
   https://pki.qualcomm.com/ssl_v4_cert.crt

ADD https://github.qualcomm.com/raw/netskope-ssl/download/main/nscacert.cer /usr/local/share/ca-certificates/netskope.crt

RUN update-ca-certificates

ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt

RUN corepack enable
RUN pnpm install --frozen-lockfile
RUN pnpm run build:react
RUN pnpm react-table-docs build
RUN pnpm --filter react-table-docs deploy --prod /app/deployed

FROM public.ecr.aws/docker/library/node:lts-slim
WORKDIR /app
COPY --from=builder /app/deployed/node_modules ./node_modules
COPY --from=builder /app/packages/docs/react-table-docs/build ./build
COPY --from=builder /app/packages/docs/react-table-docs/package.json ./package.json
ENV NODE_ENV=production
EXPOSE 3000
CMD ["npx", "react-router-serve", "./build/server/index.js"]
