FROM public.ecr.aws/docker/library/node:22-slim

WORKDIR /app

COPY . .

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

# install and build
RUN corepack enable
RUN pnpm install

RUN pnpx playwright@1.53.2 install chromium --with-deps --only-shell

RUN pnpm run build
RUN pnpm angular-docs build:prod
ENV NODE_ENV=production

EXPOSE 3000

CMD ["pnpm", "run", "-C", "packages/docs/angular-docs", "start"]
