// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {DummyRuleMap} from "oxlint"

const correctness: DummyRuleMap = {
  "unicorn/no-await-in-promise-methods": "error",
  "unicorn/no-empty-file": "off",
  "unicorn/no-invalid-fetch-options": "error",
  "unicorn/no-invalid-remove-event-listener": "error",
  // handled by eslint / typescript plugins
  "unicorn/no-new-array": "off",
  "unicorn/no-single-promise-in-promise-methods": "off",
  "unicorn/no-thenable": "off",
  "unicorn/no-unnecessary-await": "error",
  "unicorn/no-useless-fallback-in-spread": "off",
  "unicorn/no-useless-length-check": "error",
  "unicorn/no-useless-spread": "off",
  "unicorn/prefer-set-size": "error",
  "unicorn/prefer-string-starts-ends-with": "off",
}

const nursery: DummyRuleMap = {
  "unicorn/no-useless-iterator-to-array": "off",
}

const pedantic: DummyRuleMap = {
  "unicorn/consistent-assert": "off",
  "unicorn/consistent-empty-array-spread": "off",
  "unicorn/escape-case": "off",
  "unicorn/explicit-length-check": "off",
  // handled by other plugins
  "unicorn/new-for-builtins": "off",
  "unicorn/no-array-callback-reference": "off",
  "unicorn/no-hex-escape": "off",
  "unicorn/no-immediate-mutation": "off",
  "unicorn/no-instanceof-array": "off",
  "unicorn/no-lonely-if": "off",
  "unicorn/no-negated-condition": "off",
  "unicorn/no-negation-in-equality-check": "off",
  "unicorn/no-new-buffer": "off",
  "unicorn/no-object-as-default-parameter": "off",
  "unicorn/no-static-only-class": "error",
  "unicorn/no-this-assignment": "off",
  "unicorn/no-typeof-undefined": "off",
  "unicorn/no-unnecessary-array-flat-depth": "off",
  "unicorn/no-unnecessary-array-splice-count": "off",
  "unicorn/no-unnecessary-slice-end": "off",
  "unicorn/no-unreadable-iife": "error",
  "unicorn/no-useless-promise-resolve-reject": "off",
  "unicorn/no-useless-switch-case": "off",
  "unicorn/no-useless-undefined": "off",
  "unicorn/prefer-array-flat": "off",
  "unicorn/prefer-array-some": "off",
  "unicorn/prefer-at": "warn",
  "unicorn/prefer-blob-reading-methods": "off",
  "unicorn/prefer-code-point": "off",
  "unicorn/prefer-date-now": "warn",
  "unicorn/prefer-dom-node-append": "off",
  "unicorn/prefer-dom-node-dataset": "off",
  "unicorn/prefer-dom-node-remove": "off",
  "unicorn/prefer-event-target": "off",
  "unicorn/prefer-import-meta-properties": "off",
  "unicorn/prefer-math-min-max": "off",
  "unicorn/prefer-math-trunc": "off",
  "unicorn/prefer-native-coercion-functions": "off",
  "unicorn/prefer-prototype-methods": "off",
  "unicorn/prefer-query-selector": "off",
  "unicorn/prefer-regexp-test": "off",
  "unicorn/prefer-string-replace-all": "off",
  "unicorn/prefer-string-slice": "off",
  "unicorn/prefer-top-level-await": "off",
  "unicorn/prefer-type-error": "off",
  "unicorn/require-number-to-fixed-digits-argument": "off",
}

const perf: DummyRuleMap = {
  "unicorn/prefer-array-find": "error",
  "unicorn/prefer-array-flat-map": "off",
  "unicorn/prefer-set-has": "off",
}

const restriction: DummyRuleMap = {
  "unicorn/import-style": "off",
  "unicorn/no-abusive-eslint-disable": "off",
  "unicorn/no-anonymous-default-export": "off",
  "unicorn/no-array-for-each": "warn",
  "unicorn/no-array-reduce": "off",
  "unicorn/no-document-cookie": "off",
  "unicorn/no-length-as-slice-end": "off",
  "unicorn/no-magic-array-flat-depth": "off",
  "unicorn/no-process-exit": "off",
  "unicorn/no-useless-error-capture-stack-trace": "off",
  "unicorn/prefer-modern-math-apis": "off",
  "unicorn/prefer-module": "off",
  "unicorn/prefer-node-protocol": "error",
  "unicorn/prefer-number-properties": "off",
}

const style: DummyRuleMap = {
  "unicorn/catch-error-name": "off",
  "unicorn/consistent-date-clone": "off",
  "unicorn/consistent-existence-index-check": "off",
  "unicorn/consistent-template-literal-escape": "off",
  "unicorn/custom-error-definition": "off",
  "unicorn/empty-brace-spaces": "off",
  "unicorn/error-message": "off",
  "unicorn/filename-case": "off",
  "unicorn/no-array-method-this-argument": "off",
  "unicorn/no-await-expression-member": "off",
  "unicorn/no-console-spaces": "off",
  "unicorn/no-nested-ternary": "off",
  "unicorn/no-null": "off",
  "unicorn/no-unreadable-array-destructuring": "off",
  "unicorn/no-useless-collection-argument": "off",
  "unicorn/no-zero-fractions": "off",
  "unicorn/number-literal-case": "off",
  "unicorn/numeric-separators-style": "off",
  "unicorn/prefer-array-index-of": "off",
  "unicorn/prefer-bigint-literals": "off",
  "unicorn/prefer-class-fields": "off",
  "unicorn/prefer-classlist-toggle": "off",
  "unicorn/prefer-default-parameters": "off",
  "unicorn/prefer-dom-node-text-content": "off",
  "unicorn/prefer-global-this": "off",
  "unicorn/prefer-includes": "off",
  "unicorn/prefer-keyboard-event-key": "off",
  "unicorn/prefer-logical-operator-over-ternary": "off",
  "unicorn/prefer-modern-dom-apis": "off",
  "unicorn/prefer-negative-index": "off",
  "unicorn/prefer-object-from-entries": "off",
  "unicorn/prefer-optional-catch-binding": "off",
  "unicorn/prefer-reflect-apply": "off",
  "unicorn/prefer-response-static-json": "off",
  "unicorn/prefer-spread": "off",
  "unicorn/prefer-string-raw": "off",
  "unicorn/prefer-string-trim-start-end": "error",
  "unicorn/prefer-structured-clone": "off",
  "unicorn/prefer-ternary": "off",
  "unicorn/relative-url-style": "off",
  "unicorn/require-array-join-separator": "off",
  "unicorn/require-module-attributes": "off",
  "unicorn/switch-case-braces": "off",
  "unicorn/switch-case-break-position": "off",
  "unicorn/text-encoding-identifier-case": "off",
  "unicorn/throw-new-error": "off",
}

const suspicious: DummyRuleMap = {
  "unicorn/consistent-function-scoping": "off",
  "unicorn/no-accessor-recursion": "off",
  "unicorn/no-array-reverse": "off",
  "unicorn/no-array-sort": "off",
  "unicorn/no-instanceof-builtins": "off",
  "unicorn/prefer-add-event-listener": "off",
  "unicorn/require-module-specifiers": "off",
  "unicorn/require-post-message-target-origin": "off",
}

export const unicornRules: DummyRuleMap = {
  ...correctness,
  ...nursery,
  ...pedantic,
  ...perf,
  ...restriction,
  ...style,
  ...suspicious,
}
