import type {Routes} from "@angular/router"

import {
  AccordionPage,
  AlertBannerPage,
  AvatarPage,
  BreadcrumbsPage,
  ButtonGroupPage,
  ButtonPage,
  CardPage,
  CheckboxGroupPage,
  CheckboxPage,
  CollapsiblePage,
  ComboboxPage,
  DatePickerPage,
  DialogPage,
  DividerPage,
  DrawerPage,
  FileInputPage,
  HeaderBarPage,
  IconButtonPage,
  IconPage,
  InlineIconButtonPage,
  InlineNotificationPage,
  LinkPage,
  MenuPage,
  NumberInputPage,
  PaginationPage,
  PasswordInputPage,
  PopoverPage,
  ProgressPage,
  ProgressRingPage,
  RadioPage,
  SegmentedControlPage,
  SelectPage,
  SideNavPage,
  SliderPage,
  StepperPage,
  SwitchGroupPage,
  SwitchPage,
  TabsPage,
  TagPage,
  TextAreaPage,
  TextInputPage,
  ToastPage,
  TooltipPage,
  TreePage,
} from "./components"
import {Home} from "./home"

export const routes: Routes = [
  {component: Home, path: ""},
  {component: AccordionPage, path: "accordion"},
  {component: AlertBannerPage, path: "alert-banner"},
  {component: AvatarPage, path: "avatar"},
  {component: BreadcrumbsPage, path: "breadcrumbs"},
  {component: ButtonPage, path: "button"},
  {component: ButtonGroupPage, path: "button-group"},
  {component: CardPage, path: "card"},
  {component: CheckboxPage, path: "checkbox"},
  {component: CheckboxGroupPage, path: "checkbox-group"},
  {component: CollapsiblePage, path: "collapsible"},
  {component: ComboboxPage, path: "combobox"},
  {component: DatePickerPage, path: "date-picker"},
  {component: DialogPage, path: "dialog"},
  {component: DividerPage, path: "divider"},
  {component: DrawerPage, path: "drawer"},
  {component: FileInputPage, path: "file-input"},
  {component: HeaderBarPage, path: "header-bar"},
  {component: IconPage, path: "icon"},
  {component: IconButtonPage, path: "icon-button"},
  {component: InlineIconButtonPage, path: "inline-icon-button"},
  {component: InlineNotificationPage, path: "inline-notification"},
  {component: LinkPage, path: "link"},
  {component: MenuPage, path: "menu"},
  {component: NumberInputPage, path: "number-input"},
  {component: PaginationPage, path: "pagination"},
  {component: PasswordInputPage, path: "password-input"},
  {component: PopoverPage, path: "popover"},
  {component: ProgressPage, path: "progress"},
  {component: ProgressRingPage, path: "progress-ring"},
  {component: RadioPage, path: "radio"},
  {component: SegmentedControlPage, path: "segmented-control"},
  {component: SelectPage, path: "select"},
  {component: SideNavPage, path: "side-nav"},
  {component: SliderPage, path: "slider"},
  {component: StepperPage, path: "stepper"},
  {component: SwitchPage, path: "switch"},
  {component: SwitchGroupPage, path: "switch-group"},
  {component: TabsPage, path: "tabs"},
  {component: TagPage, path: "tag"},
  {component: TextAreaPage, path: "text-area"},
  {component: TextInputPage, path: "text-input"},
  {component: ToastPage, path: "toast"},
  {component: TooltipPage, path: "tooltip"},
  {component: TreePage, path: "tree"},
]
