export type {DialogBackdropProps} from "./dialog-backdrop"
export type {DialogBodyProps} from "./dialog-body"
export type {DialogCloseButtonProps} from "./dialog-close-button"
export type {DialogCloseTriggerProps} from "./dialog-close-trigger"
export type {DialogContentProps} from "./dialog-content"
export type {DialogDescriptionProps} from "./dialog-description"
export type {DialogFloatingPortalProps} from "./dialog-floating-portal"
export type {DialogFooterProps} from "./dialog-footer"
export type {DialogHeadingProps} from "./dialog-heading"
export type {DialogIndicatorIconProps} from "./dialog-indicator-icon"
export type {DialogPositionerProps} from "./dialog-positioner"
export type {DialogRootProps} from "./dialog-root"
export type {DialogTriggerProps} from "./dialog-trigger"

export {Dialog} from "./dialog"
