name: Deploy Angular Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/common/**
      - packages/frameworks/react*/**
      - packages/frameworks/angular*/**
      - packages/docs/angular-docs/**

jobs:
  deploy:
    uses: ./.github/workflows/reusable-docs-deploy-test.yml
    with:
      dockerfile: dockerfiles/dockerfile-angular-docs
      ecr-repository-name: angular-next
    secrets: inherit
