name: Deploy React Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/common/**
      - packages/frameworks/react*/**
      - packages/docs/react-docs/**

jobs:
  deploy:
    uses: ./.github/workflows/reusable-docs-deploy.yml
    with:
      dockerfile: dockerfiles/dockerfile-react-docs
      ecr-repository-name: react-next-docs
    secrets: inherit
