name: Deploy React Table Docs

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-docs-deploy.yml
    with:
      dockerfile: dockerfiles/dockerfile-react-table-docs
      ecr-repository-name: react-table-next
      eks-deployment-name: react-table-next
      container-name: react-table-next
      aws-region: us-west-2
      namespace: qui
    secrets:
      AWS_ECR_ACCESS_KEY_ID: ${{ secrets.QUI_DOCS_AWS_ECR_ACCESS_KEY }}
      AWS_ECR_SECRET_ACCESS_KEY: ${{ secrets.QUI_DOCS_AWS_ECR_SECRET_ACCESS_KEY }}
      AWS_EKS_ACCESS_KEY_ID: ${{ secrets.QUI_DOCS_AWS_EKS_ACCESS_KEY }}
      AWS_EKS_SECRET_ACCESS_KEY: ${{ secrets.QUI_DOCS_AWS_EKS_SECRET_ACCESS_KEY }}
      ECR_REGISTRY_URL: ${{ secrets.QUI_DOCS_ECR_REGISTRY_URL }}
      EKS_CLUSTER_NAME: ${{ secrets.QUI_DOCS_EKS_CLUSTER_NAME }}
