name: Deploy QUI Docs

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-docs-deploy-prod.yml
    with:
      dockerfile: dockerfiles/dockerfile-qui-docs
      ecr-repository-name: qui-docs
    secrets: inherit
