name: Deploy React Table Docs

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-docs-deploy-prod.yml
    with:
      dockerfile: dockerfiles/dockerfile-react-table-docs
      ecr-repository-name: react-table-docs
    secrets: inherit
