name: "Publish Packages and Create Releases"
env:
  IS_CI: true
  TURBO_API: "http://127.0.0.1:8585"
  TURBO_TEAM: "qualcomm-ui"
  TURBO_TOKEN: "turbo-cache-token"
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'packages/**/CHANGELOG.md'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should-publish: ${{ steps.check.outputs.should-publish }}
    steps:
    - uses: actions/checkout@v6

    - uses: ./.github/actions/init-node-and-install

    - id: check
      run: pnpm qui-changesets check-versions

  publish:
    needs: check
    if: needs.check.outputs.should-publish == 'true'
    runs-on: ubuntu-latest
    concurrency:
      group: Publish Packages - ${{github.head_ref}}
      cancel-in-progress: true
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v6

    - uses: ./.github/actions/init-node-and-install

    - uses: ./.github/actions/init-remote-cache
      with:
        turborepo-remote-cache-bucket-name: ${{ secrets.TURBOREPO_REMOTE_CACHE_BUCKET_NAME }}
        turborepo-remote-cache-access-key: ${{ secrets.TURBOREPO_REMOTE_CACHE_ACCESS_KEY }}
        turborepo-remote-cache-secret-key: ${{ secrets.TURBOREPO_REMOTE_CACHE_SECRET_KEY }}

    - name: build
      run: pnpm run build

    - run: npm --version

    - name: publish
      run: pnpm publish:all

    - name: create releases
      run: pnpm qui-changesets create-github-releases --token $TOKEN
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
