name: Reusable Docs Deploy

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      ecr-repository-name:
        required: true
        type: string
      aws-region:
        type: string
        default: us-west-2
    secrets:
      QUI_DOCS_AWS_ECR_ACCESS_KEY:
        required: true
      QUI_DOCS_AWS_ECR_SECRET_ACCESS_KEY:
        required: true
      QUI_DOCS_ECR_REGISTRY_URL:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # full history for docs site builds

    - name: Log in to ECR
      run: |
        aws ecr get-login-password --region ${{ inputs.aws-region }} | \
          docker login --username AWS --password-stdin ${{ secrets.QUI_DOCS_ECR_REGISTRY_URL }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.QUI_DOCS_AWS_ECR_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.QUI_DOCS_AWS_ECR_SECRET_ACCESS_KEY }}

    - name: Build and push
      run: |
        docker build \
          --network=host \
          --platform=linux/amd64 \
          --progress=plain \
          --no-cache \
          -t ${{ secrets.QUI_DOCS_ECR_REGISTRY_URL }}/${{ inputs.ecr-repository-name }}:${{ github.sha }} \
          -f ${{ inputs.dockerfile }} .
        docker push \
          ${{ secrets.QUI_DOCS_ECR_REGISTRY_URL }}/${{ inputs.ecr-repository-name }} \
          --all-tags
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.QUI_DOCS_AWS_ECR_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.QUI_DOCS_AWS_ECR_SECRET_ACCESS_KEY }}
